apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: git-operation
spec:
  templates:
  - name: git-clone
    inputs:
      artifacts:
      - name: argo-source
        path: /src
        git:
          repo: https://github.com/argoproj/argo-workflows.git
          revision: "v2.1.1"
          # usernameSecret:
          #   name: github-creds
          #   key: username
          # passwordSecret:
          #   name: github-creds
          #   key: password
          # sshPrivateKeySecret:
          #   name: github-creds
          #   key: ssh-private-key
          # depth: 1
          # fetch: refs/meta/*
          # fetch: refs/changes/*
          # singleBranch: true
          # branch: my-branch
    container:
      image: golang:1.10
      command: [sh, -c]
      args: ["git status && ls && cat VERSION"]
      workingDir: /src






    # - name: git-clone
    #   inputs:
    #     parameters:
    #       - name: gitRepo
    #         value: "https://github.com/argoproj/argo-workflows.git"
    #       - name: gitBranch
    #         value: "main"
    #     artifacts:
    #       - name: terraform-source
    #         path: /src
    #         git:
    #           repo: "{{inputs.parameters.gitBranch}}"
    #           revision: "{{inputs.parameters.gitBranch}}"
    #   container:
    #     image: golang:1.10
    #     command: [sh, -c]
    #     args: ["git status && ls && ls -lah"]
    #     workingDir: /src