creation_rules:
    - path_regex:  \.test\.tf$
      hc_vault_transit_uri: "http://127.0.0.1:8200/v1/sops/keys/firstkey"
    - path_regex: \.yaml.secret$
      hc_vault_transit_uri: "http://127.0.0.1:8200/v1/sops/keys/secondkey"
    - path_regex: \.prod\.yaml$
      hc_vault_transit_uri: "http://127.0.0.1:8200/v1/sops/keys/thirdkey"
