apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: terraform-job
spec:
  # schedule: "* * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0

  # workflowSpec:
  entrypoint: start-terraform-job

  templates:
    - name: start-terraform-job
      steps:
      - - name: get-now
          templateRef:
            name: get-now
            template: get-now

      - - name: clone-terraform-code-from-git
          templateRef:
            name: git-operation
            template: git-clone

