apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: terraform-cronjob-02
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: "Forbid"
  # startingDeadlineSeconds: 0
  successfulJobsHistoryLimit: 6
  failedJobsHistoryLimit: 3

  workflowSpec:
    entrypoint: start-terraform-job-02
    # arguments:
    archiveLogs: true

    templates:
      - name: start-terraform-job-02
        steps:
        - - name: get-now
            templateRef:
              name: get-now
              template: get-now
        - - name: clone-terraform-code-from-git
            templateRef:
              name: git-operation-03
              template: git-clone-03
            arguments:
              parameters:
              - name: gitRepo
                value: https://github.com/OlafRadicke/daytona_beach.git
              - name: gitBranch
                value: "main"
        - - name: get-version-of-terragrunt
            templateRef:
              name: terragrunt-operation
              template: get-version
        - - name: list-content-of-terragrunt-dir
            templateRef:
              name: terragrunt-operation
              template: get-content-of-dir
