apiVersion:           argoproj.io/v1alpha1
kind:                 WorkflowTemplate
metadata:
  name:               terragrunt-operation-04
spec:
  templates:


    - name:           get-content-of-dir
      container:
        image:        alpine/terragrunt:1.10.3
        command:      [sh, -c]
        args:         ["ls -lah "]
        workingDir:   /src/clone
        volumeMounts:
        - name:       argo-workdir
          mountPath:  /src


    - name:           get-version
      container:
        image:        alpine/terragrunt:1.10.3
        command:      [terraform]
        args:
                      - "version"
        workingDir:   /src/clone
        volumeMounts:
        - name:       argo-workdir
          mountPath:  /src


    - name:           run-terraform-init
      container:
        image:        alpine/terragrunt:1.10.3
        command:      [terraform]
        args:
                      - "init"
        workingDir:   /src/clone/terraform/examples
        volumeMounts:
        - name:       tofu-backend-vol
          mountPath:  /terraform/state/
        - name:       argo-workdir
          mountPath:  /src