apiVersion:         argoproj.io/v1alpha1
kind:               WorkflowTemplate
metadata:
  name:             sops-operation
spec:
  templates:
    - name:         get-version
      container:
        image:      docker.io/olafradicke/alpine-sops:0.7.2
        args:       ["--version"]

    - name:         get-conten-of-dir
      container:
        image:      docker.io/olafradicke/alpine-sops:0.7.2
        command:    [sh, -c]
        args:       ["ls -lah"]
        workingDir: "{{workflow.parameters.example-path}}"
        volumeMounts:
        - name:     argo-workdir
          mountPath: /src

    - name:         decrypt
      container:
        image:      docker.io/olafradicke/fedora-sops:0.7.12-ci
        env:
        - name:     VAULT_ADDR
          value:    'http://vault-server.vault:8200'
        - name:     VAULT_TOKEN
          value:    'ChaNG_mE,plEAse!!'
        command:    [sh, -c]
        args:
                    - |
                      sops --decrypt \
                      --config <(echo '') \
                      --hc-vault-transit $VAULT_ADDR/v1/sops/keys/default \
                      terragrunt.hcl.sops > terragrunt.hcl
        workingDir: "{{workflow.parameters.example-path}}"
        volumeMounts:
        - name:     argo-workdir
          mountPath: /src