apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name:           terragrunt-operation-04
spec:
  templates:
    - name:       get-version
      container:
        image:    alpine/terragrunt:1.10.3
        command:  [terraform]
        args:
                  - "version"

    - name:       get-content-of-dir
      inputs:
        artifacts:
        - name:   input-git-clone-src-04
          path:   /src
      container:
        image:    alpine/terragrunt:1.10.3
        command:  [sh, -c]
        args:     ["ls -lah"]
