apiVersion:         argoproj.io/v1alpha1
kind:               WorkflowTemplate
metadata:
  name:             sops-operation
spec:
  templates:
    - name:         get-version
      container:
        image:      docker.io/olafradicke/alpine-sops:0.7.2
        # command:  [sh, -c]
        args:       ["--version"]

    - name:         get-conten-of-dir
      container:
        image:      docker.io/olafradicke/alpine-sops:0.7.2
        command:    [sh, -c]
        args:       ["ls -lah"]
        workingDir: /src/clone/terraform/examples-01
        volumeMounts:
        - name:     argo-workdir
          mountPath: /src


    - name:         reset-server
      container:
        image:      docker.io/olafradicke/alpine-sops:0.7.2
        args:
                    - |
                      set terragrunt.hcl.sops '["hc_vault"]["vault_address"]' '"http://vault-server.vault:8200"'
        workingDir: /src/clone/terraform/examples-01
        volumeMounts:
        - name:     argo-workdir
          mountPath: /src

    - name:         decrypt
      container:
        image:      docker.io/olafradicke/alpine-sops:0.7.2
        env:
        - name:     VAULT_ADDR
          value:    'http://vault-server.vault:8200'
        - name:     VAULT_TOKEN
          value:    'ChaNG_mE,plEAse!!'
        args:
                    - |
                      decrypt \
                      --keyservice 'http://vault-server.vault:8200' \
                      terragrunt.hcl.sops > terragrunt.hcl
        workingDir: /src/clone/terraform/examples-01
        volumeMounts:
        - name:     argo-workdir
          mountPath: /src