apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: terragrunt-operation
spec:
  templates:
    - name: get-version
      container:
        image: alpine/terragrunt:1.10.3
        command: [terraform]
        args: ["version"]
    - name: get-content-of-dir
      container:
        image: alpine/terragrunt:1.10.3
        command: ["/bin/sh","-c"]
        args:
          - "ls -lah"
          - "date"
    - name: get-content-of-dir-03
      inputs:
        artifacts:
        - name: git-clone-src-03
          path:  /src
      container:
        image: alpine/terragrunt:1.10.3
        command: ["/bin/sh","-c"]
        args:
          - "ls -lah"
          - "date"
