apiVersion:         argoproj.io/v1alpha1
kind:               WorkflowTemplate
metadata:
  name:             git-operation-04
spec:
  templates:

    - name:         git-clone
      inputs:
        parameters:
          - name:   gitRepo
          - name:   gitBranch
      initContainers:
        - image:    k8s.gcr.io/git-sync:v3.1.6
          args:
                    - "--repo={{inputs.parameters.gitRepo}}"
                    - "--root=/src/clone"
                    - "--max-sync-failures=3"
                    - "--timeout=200"
                    - "--branch={{inputs.parameters.gitBranch}}"
                    # - "--ssh"
                    - "--one-time"
          name:     git-data
          volumeMounts:
            - name: argo-workdir
              mountPath: /src
            # - name: git-secret
            #   mountPath: /etc/git-secret
      container:
        image:      golang:1.10
        command:    [sh, -c]
        args:       ["ls -lah && git branch && git checkout {{inputs.parameters.gitBranch}} && git status && ls -lah  && ls -lah terraform/examples "]
        workingDir: /src/clone
        volumeMounts:
        - name:     argo-workdir
          mountPath: /src

