apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name:           terragrunt-operation-04
spec:
  templates:
    - name:       get-version
      container:
        image:    alpine/terragrunt:1.10.3
        command:  [terraform]
        args:
                  - "version"

    - name:       get-content-of-dir
      inputs:
        artifacts:
        - name:   in-git-clone-src-04
          path:   /src
      container:
        image:    alpine/terragrunt:1.10.3
        command:  [sh, -c]
        args:     ["ls -lah"]


    - name:       get-content-of-dir-2
      artifacts:
      - name:     git-clone-src-04
        path:     /src
        git:
          repo:   "{{inputs.parameters.gitRepo}}"
          # revision: "{{inputs.parameters.gitBranch}}"
          branch: "{{inputs.parameters.gitBranch}}"
          singleBranch: true
      container:
        image:    alpine/terragrunt:1.10.3
        command:  [sh, -c]
        args:     ["ls -lah"]