apiVersion:       argoproj.io/v1alpha1
kind:             WorkflowTemplate
metadata:
  name:           vault-operation
spec:
  templates:

    - name:       get-vault-status
      container:
        image:    docker.io/olafradicke/alpine-vault:0.7.4-ci
        env:
        - name: VAULT_ADDR
          value: 'http://vault-server.vault:8200'
        - name: VAULT_TOKEN
          value: 'ChaNG_mE,plEAse!!'
        # command:  [sh, -c]
        args:     ["status"]
        workingDir: /src/clone
        volumeMounts:
        - name:     argo-workdir
          mountPath: /src