apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name:           get-date-04
spec:
  templates:
    - name:       get-now
      container:
        image:    alpine:3.6
        command:  [sh, -c]
        args:     ["date"]

    - name:       get-conten-of-dir
      inputs:
        artifacts:
        - name:   git-clone-src-04
          path:   /src
      container:
        image:    alpine:3.6
        command:  [sh, -c]
        args:     ["ls -lah /src"]

