---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
  labels:
    type: local
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/pv-local-storage"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 100Mi