apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-server
  labels:
    app: vault-server
spec:
  selector:
    matchLabels:
      app: vault-server
  template:
    metadata:
      labels:
        app: vault-server
    spec:
      containers:
      - name: vault-server
        image: "vault:1.13.3"
        ports:
        - containerPort: 8200
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: 'ChaNG_mY'
        command: ["vault"]
        args:
          - "server"
          - "-config"
          - "/vault/config.d"
        resources:
          requests:
            cpu: 50m
            memory: "10Mi"
          limits:
            cpu: 700m
            memory: "200Mi"
        volumeMounts:
        - name: config
          mountPath: /vault/config.d
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: local-storage

    # spec:
    #   accessModes: [ "ReadWriteOnce" ]
    #   storageClassName: local-storage
    #   resources:
    #     requests:
    #       storage: 100Mi




