

# Statless setup

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-server
  labels:
    app: vault-server
spec:
  selector:
    matchLabels:
      app: vault-server
  template:
    metadata:
      labels:
        app: vault-server
    spec:
      containers:
      - name: vault-server
        image: "vault:1.13.3"
        ports:
        - containerPort: 8200
          name: http
        env:
        # - name: VAULT_DEV_ROOT_TOKEN_ID
        #   value: 'ChaNG_mE,plEAse!!'
        - name:     VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key:  token
        - name: VAULT_LOCAL_CONFIG
          value: '{"storage": {"file": {"path": "/vault/file"}}, "listener": [{"tcp": { "address": "0.0.0.0:8202", "tls_disable": true}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h", "ui": true}'
        resources:
          requests:
            cpu: 50m
            memory: "10Mi"
          limits:
            cpu: 700m
            memory: "200Mi"


# ---


#  This will be not work in dev mode. See: https://github.com/hashicorp/vault/issues/12004

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: vault-server
#   labels:
#     app: vault-server
# spec:
#   selector:
#     matchLabels:
#       app: vault-server
#   template:
#     metadata:
#       labels:
#         app: vault-server
#     spec:
#       containers:
#       - name: vault-server
#         image: "vault:1.13.3"
#         ports:
#         - containerPort: 8200
#           name: http
#         - containerPort: 8201
#           name: http-api
#         env:
#         - name: VAULT_DEV_LISTEN_ADDRESS
#           value: '0.0.0.0:8200'
#         - name: VAULT_API_ADDR
#           value: 'http://vault-server:8201'
#         - name: VAULT_DISABLE_MLOCK
#           value: 'true'
#         - name: SKIP_SETCAP
#           value: 'true'
#         - name: VAULT_DEV_ROOT_TOKEN_ID
#           value: 'ChaNG_mY'
#         - name: VAULT_LOCAL_CONFIG
#           value: '{"storage": {"file": {"path": "/vault/file"}}, "listener": [{"tcp": { "address": "0.0.0.0:8202", "tls_disable": true}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h", "ui": true}'
#         resources:
#           requests:
#             cpu: 50m
#             memory: "10Mi"
#           limits:
#             cpu: 700m
#             memory: "200Mi"
#         volumeMounts:
#         - name: config
#           mountPath: /vault/file
#       volumes:
#       - name: config
#         persistentVolumeClaim:
#           claimName: local-storage