apiVersion: v1
kind: Service
metadata:
  name: vault-server
  labels:
    app: vault-server
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8200
    targetPort: http
  clusterIP: None
  selector:
    app: vault-server