apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: terraform-cronjob
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Forbid"
  # startingDeadlineSeconds: 0

  workflowSpec:
    entrypoint: start-terraform-job
    # arguments:
    archiveLogs: true

    templates:
      - name: start-terraform-job
        steps:
        - - name: get-now
            templateRef:
              name: get-now
              template: get-now
        - - name: clone-terraform-code-from-git
            templateRef:
              name: git-operation
              template: git-clone

