apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: terraform-cronjob
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: "Forbid"
  # startingDeadlineSeconds: 0
  successfulJobsHistoryLimit: 6
  failedJobsHistoryLimit: 3

  workflowSpec:
    entrypoint: start-terraform-job
    # arguments:
    archiveLogs: true

    templates:
      - name: start-terraform-job
        steps:
        - - name: get-now
            templateRef:
              name: get-now
              template: get-now
        - - name: clone-terraform-code-from-git
            templateRef:
              name: git-operation
              template: git-clone
        - - name: get-version-of-terragrunt
            templateRef:
              name: terragrunt-operation
              template: get-version
        - - name: list-content-of-terragrunt-dir
            templateRef:
              name: terragrunt-operation
              template: get-content-of-dir
