apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name:                 terraform-cronjob-04
spec:
  schedule:             "*/1 * * * *"
  concurrencyPolicy:    "Forbid"
  # startingDeadlineSeconds: 0
  successfulJobsHistoryLimit: 6
  failedJobsHistoryLimit: 3

  workflowSpec:
    entrypoint:         start-terraform-job-04
    archiveLogs:        true

    templates:
      - name:           start-terraform-job-04
        steps:

        - - name:       get-date-04
            templateRef:
              name:     get-date-04
              template: get-now

        - - name:       clone-terraform-code-from-git
            templateRef:
              name:     git-operation-04
              template: git-clone-04
            arguments:
              parameters:
              - name:   gitRepo
                value:  https://github.com/OlafRadicke/daytona_beach.git
              - name:   gitBranch
                value:  "main"

        - - name:       get-dat-2
            templateRef:
              name:     get-date-04
              template: get-now

        # - - name:       get-dir
        #     templateRef:
        #       name:     get-date-04
        #       template: get-conten-of-dir
        #     arguments:
        #       artifacts:
        #       - name: git-clone-src-04
        #         from: "{{steps.clone-terraform-code-from-git.outputs.artifacts.git-clone-src-04}}"

        # - - name:       list-content-of-terragrunt-dir
        #     templateRef:
        #       name:     terragrunt-operation-04
        #       template: get-content-of-dir
        #     arguments:
        #       artifacts:
        #       - name: input-git-clone-src-04
        #         from: "{{steps.clone-terraform-code-from-git.outputs.artifacts.git-clone-src-04}}"


        # - - name:       get-version-of-terragrunt
        #     templateRef:
        #       name:     terragrunt-operation-04
        #       template: get-version

