apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name:                 terraform-job
spec:
  entrypoint:           start-terraform-job
  # Temp pvc
  volumeClaimTemplates:
    - metadata:
        name:           argo-workdir
      spec:
        accessModes:    [ "ReadWriteOnce" ]
        resources:
          requests:
            storage:    1Gi
  # Persistent pvc
  volumes:
    - name:             tofu-backend-vol
      persistentVolumeClaim:
        claimName:      tofu-backend

  templates:
    - name:             start-terraform-job
      steps:

# vault

        - - name:       vault-get-status
            templateRef:
              name:     vault-operation
              template: get-vault-status

#  git


        - - name:       clone-terraform-code-from-git
            templateRef:
              name:     git-operation
              template: git-clone
            arguments:
              parameters:
              - name:   gitRepo
                value:  https://github.com/OlafRadicke/daytona_beach.git
              - name:   gitBranch
                value:  "main"

# vault

        - - name:       vault-enable-transit
            templateRef:
              name:     vault-operation
              template: enable-transit
            continueOn:
              failed: true

        - - name:       vault-create-key
            templateRef:
              name:     vault-operation
              template: create-key

# sops
        - - name:       sops-get-version
            templateRef:
              name:     sops-operation
              template: get-version

        - - name:       sops-get-conten-of-dir
            templateRef:
              name:     sops-operation
              template: get-conten-of-dir



# terragrunt
        # - - name:       terragrunt-get-version
        #     templateRef:
        #       name:     terragrunt-operation
        #       template: get-terragrunt-version

        # - - name:       terraform-run-init
        #     templateRef:
        #       name:     terragrunt-operation
        #       template: run-terraform-init

        # - - name:       terraform-run-plan
        #     templateRef:
        #       name:     terragrunt-operation
        #       template: run-terraform-plan

        # - - name:       terraform-run-apply
        #     templateRef:
        #       name:     terragrunt-operation
        #       template: run-terraform-apply