apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name:                 terraform-job
spec:
  entrypoint:           start-terraform-job
  # Global arguments for WorkflowTemplates
  arguments:
    parameters:
    - name:             example-path
      value:            /src/clone/terraform/examples-01
  # Temp pvc
  volumeClaimTemplates:
    - metadata:
        name:           argo-workdir
      spec:
        accessModes:    [ "ReadWriteOnce" ]
        resources:
          requests:
            storage:    1Gi
  # Persistent pvc
  volumes:
    - name:             tofu-backend-vol
      persistentVolumeClaim:
        claimName:      tofu-backend

  templates:
    - name:             start-terraform-job
      steps:

# vault
# Checks the connection to the Vaultserver

        - - name:       vault-get-status
            templateRef:
              name:     vault-operation
              template: get-vault-status

# git
# Clone the Terraform code from a Git repository

        - - name:       clone-terraform-code-from-git
            templateRef:
              name:     git-operation
              template: git-clone
            arguments:
              parameters:
              - name:   gitRepo
                value:  https://github.com/OlafRadicke/daytona_beach.git
              - name:   gitBranch
                value:  "main"

# Vault Server setup

        # # Enable transit support for Vault server
        # - - name:       vault-enable-transit
        #     templateRef:
        #       name:     vault-operation
        #       template: enable-transit
        #     continueOn:
        #       failed: true

        # #  Create a default key (for example)
        # - - name:       vault-create-key
        #     templateRef:
        #       name:     vault-operation
        #       template: create-key

# Mozilla SOPS operations

        # Check the version of SOPS
        - - name:       sops-get-version
            templateRef:
              name:     sops-operation
              template: get-version

        # List the conten of the git clone before the
        # the secrets a be decrypted.
        - - name:       sops-get-conten-of-dir-before
            templateRef:
              name:     sops-operation
              template: get-conten-of-dir

        # Decrypt the secret with help of SOPS and the
        # Vault server.
        - - name:       decrypt
            templateRef:
              name:     sops-operation
              template: decrypt

        # List the conten fof die example directory after
        # decryption operation.
        - - name:       sops-get-conten-of-dir-after
            templateRef:
              name:     sops-operation
              template: get-conten-of-dir

# terragrunt

        - - name:       terragrunt-get-content-of-dir
            templateRef:
              name:     terragrunt-operation
              template: get-content-of-dir

        - - name:       terragrunt-get-version
            templateRef:
              name:     terragrunt-operation
              template: get-terragrunt-version

        - - name:       terraform-run-init
            templateRef:
              name:     terragrunt-operation
              template: run-terraform-init

        - - name:       terraform-run-plan
            templateRef:
              name:     terragrunt-operation
              template: run-terraform-plan

        - - name:       terraform-run-apply
            templateRef:
              name:     terragrunt-operation
              template: run-terraform-apply