apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name:                 terraform-job
spec:
  entrypoint:           start-terraform-job
  # Temp pvc
  volumeClaimTemplates:
    - metadata:
        name:           argo-workdir
      spec:
        accessModes:    [ "ReadWriteOnce" ]
        resources:
          requests:
            storage:    1Gi
  # Persistent pvc
  volumes:
    - name:             tofu-backend-vol
      persistentVolumeClaim:
        claimName:      tofu-backend

  templates:
    - name:             start-terraform-job
      steps:

# vault

        - - name:       vault-operation
            templateRef:
              name:     vault-operation
              template: get-vault-status

#  git

        - - name:       clone-terraform-code-from-git
            templateRef:
              name:     git-operation-04
              template: git-clone
            arguments:
              parameters:
              - name:   gitRepo
                value:  https://github.com/OlafRadicke/daytona_beach.git
              - name:   gitBranch
                value:  "main"


        - - name:       clone-terraform-code-from-git-02
            templateRef:
              name:     git-operation
              template: git-clone
            arguments:
              parameters:
              - name:   gitRepo
                value:  https://github.com/OlafRadicke/daytona_beach.git
              - name:   gitBranch
                value:  "main"

# sops
        - - name:       get-sops-version
            templateRef:
              name:     sops-operation
              template: get-version

        - - name:       get-sops-conten-of-dir
            templateRef:
              name:     sops-operation
              template: get-conten-of-dir
# terragrunt
        - - name:       get-terragrunt-version
            templateRef:
              name:     terragrunt-operation
              template: get-terragrunt-version

        - - name:       run-terraform-init
            templateRef:
              name:     terragrunt-operation
              template: run-terraform-init

        - - name:       run-terraform-plan
            templateRef:
              name:     terragrunt-operation
              template: run-terraform-plan

        - - name:       run-terraform-apply
            templateRef:
              name:     terragrunt-operation
              template: run-terraform-apply